### ISSUE TITLE
App seems to crash if Alarm Listener Service is not enabled

### ISSUE THREAD

**Issue by RAPXT** [yahyatinani/flashy-alarm#40]
If my layman interpretation is correct, it seems like the app is crashing, when the Alarm Listener Service isn't enabled.

Here's a logcat (I hope it helps):

```
FATAL EXCEPTION: main
Process: com.github.whyrising.flashyalarm, PID: 12341
java.lang.RuntimeException: Unable to start receiver com.github.whyrising.flashyalarm.alarmlistenerservice.OnBootServiceStarter: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.github.whyrising.flashyalarm/.alarmlistenerservice.FlashyAlarmService }: app is in background uid UidRecord{fe42cb2 u0a310 RCVR idle change:uncached procs:1 seq(0,0,0)}
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3798)
	at android.app.ActivityThread.access$1400(ActivityThread.java:220)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1871)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.github.whyrising.flashyalarm/.alarmlistenerservice.FlashyAlarmService }: app is in background uid UidRecord{fe42cb2 u0a310 RCVR idle change:uncached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1616)
	at android.app.ContextImpl.startService(ContextImpl.java:1571)
	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
	at com.github.whyrising.flashyalarm.alarmlistenerservice.OnBootServiceStarter.onReceive(Unknown Source:77)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3789)
	... 8 more
```

**Comment by yahyatinani** [comment]
Thank you for the report. Can you also provide what Android are you using (8, 10, 13...)?

**Comment by RAPXT** [comment]
Sure, im using Android 10. I think I have solved my issue due to exclusion from battery optimization.

Before that, I think my phone maybe killed the app when it went into battery saver mode. Which led to the service above not running and thus Flashy Alarm crashing. This would be my interpretation.

Therefore it might not be a bad idea, to remind the user through a small warning at first start to turn off battery optimization.
